<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Author Robert Hillebrand - hillebrand@i-ways.de - i-ways sales solutions GmbH
 * Copyright i-ways sales solutions GmbH © 2015. All Rights Reserved.
 * License http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile
/**
 * @see \Magento\Payment\Block\Info
 * @var \Magento\Payment\Block\Info $block
 */
?>
<?php echo $block->escapeHtml(__($block->getMethod()->getTitle())); ?>{{pdf_row_separator}}

<?php if ($specificInfo = $block->getSpecificInformation()): ?>
    <?php if ($block->isPUI()): ?>
        {{pdf_row_separator}}
        <?php echo $block->escapeHtml(__('Please transfer the invoice amount to the given account within the payment deadline.')); ?>{{pdf_row_separator}}
        {{pdf_row_separator}}
    <?php endif; ?>
    <?php foreach ($specificInfo as $label => $value): ?>
        <?php echo $block->escapeHtml($label) ?>:
        <?php echo $block->escapeHtml(implode(' ', $block->getValueAsArray($value))); ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif; ?>

<?php echo $block->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())); ?>