<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Author Robert Hillebrand - hillebrand@i-ways.de - i-ways sales solutions GmbH
 * Copyright i-ways sales solutions GmbH © 2015. All Rights Reserved.
 * License http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
?>
<?php echo $block->escapeHtml(__($block->getMethod()->getTitle())); ?>
<?php if($block->isPUI()): ?>
    <p><?php echo $this->escapeHtml(__('Pay upon Invoice')); ?></p>
<?php endif; ?>
<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value):?>
            <tr>
                <th><?php echo $block->escapeHtml($label)?>:</th>
                <td>
                    <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))));?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?php echo $block->getChildHtml()?>
