<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Author Robert Hillebrand - hillebrand@i-ways.de - i-ways sales solutions GmbH
 * Copyright i-ways sales solutions GmbH © 2015. All Rights Reserved.
 * License http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml(__($block->getMethod()->getTitle()));
?>
<dl class="payment-method">
    <dt class="title"><?php /* @noEscape */ echo $title; ?></dt>
    <?php if ($specificInfo):?>
        <dd class="content">
            <?php if($block->isPui()) : ?>
            <p><?php /* @noEscape */ echo __('Please transfer the invoice amount to the given account within the payment deadline.'); ?></p>
            <?php endif; ?>
            <table class="data table">
                <caption class="table-caption"><?php /* @noEscape */ echo $title; ?></caption>
                <?php foreach ($specificInfo as $label => $value):?>
                    <tr>
                        <th scope="row"><?php echo $block->escapeHtml($label)?></th>
                        <td>
                            <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))));?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </dd>
    <?php endif;?>
</dl>
<?php echo $block->getChildHtml()?>
