<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Author Robert Hillebrand - hillebrand@i-ways.de - i-ways sales solutions GmbH
 * Copyright i-ways sales solutions GmbH © 2015. All Rights Reserved.
 * License http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * One page checkout payment methods
 *
 * @var $this Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>
<script type="text/javascript">delete window.ppp;
    if (typeof payment.parentSwitchMethod == 'undefined') {
        payment.parentSwitchMethod = payment.switchMethod;
        payment.switchMethod = function (method) {
            if (
                window.ppp != null && method != '<?php echo Iways_PayPalPlus_Model_Payment::METHOD_CODE; ?>'
                && typeof window.thirdPartyMethodObject[method] == 'undefined'
            ) {
                window.externMethodEnabled = true;
                window.ppp.deselectPaymentMethod();
            } else {
                window.externMethodEnabled = false;
            }
            try {
                $$('.ppp').each(function (element) {
                    element.removeClassName('ppp-selected')
                });
                $$('.ppp.' + method).each(function (element) {
                    element.addClassName('ppp-selected')
                });
            } catch (e) {
                console.log(e);
            }
            try {
                console.log('enable');
                if ($$('#payment-buttons-container > button').length > 0) {
                    $$('#payment-buttons-container > button')[0].enable();
                }
                if ($('onestepcheckout-place-order') != null) {
                    $('onestepcheckout-place-order').enable();
                }
                if ($$('#review-buttons-container > button').length > 0) {
                    $$('#review-buttons-container > button')[0].enable();
                }
            } catch (e) {
                console.log(e);
            }
            return this.parentSwitchMethod(method);
        }
    }
</script>
<?php
$methods = $this->getMethods();
$oneMethod = count($methods) <= 1;

$thirdPartyMethods = $this->getThirdPartyMethods();
$pppActive = $this->isPPPActive();

$hideStyle = ' style="display:none;"';
?>
<?php if (empty($methods) && !$pppActive): ?>
    <dt>
        <?php echo $this->__('No Payment Methods') ?>
    </dt>
<?php else: ?>

    <?php //else:
    foreach ($methods as $_method) :
        $_code = $_method->getCode();
        if (isset($thirdPartyMethods[$_code]) && $pppActive) {
            $hide = true;
        } else {
            $hide = false;
        }
        ?>
        <dt class="ppp <?php echo $_code ?>"<?php if ($hide || $_code == Iways_PayPalPlus_Model_Payment::METHOD_CODE) {
            echo $hideStyle;
        } ?>>
            <?php if (!$oneMethod): ?>
                <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio"
                       name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>"
                       onclick="payment.switchMethod('<?php echo $_code ?>')"
                    <?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?>
                       class="radio"/>
            <?php else: ?>
                <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>"
                                                type="radio" name="payment[method]" checked="checked"
                                                class="radio"/></span>
                <?php $oneMethod = $_code; ?>
            <?php endif; ?>
            <label for="p_method_<?php echo $_code ?>">
                <?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?>
                <?php echo $this->getMethodLabelAfterHtml($_method) ?>
            </label>
        </dt>
        <dd class="ppp <?php echo $_code ?>"<?php if ($hide) {
            echo $hideStyle;
        } ?>><?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?><?php echo $html; ?><?php endif; ?></dd>
    <?php endforeach;
endif;
?>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
    <?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
    <?php endif; ?>
    //]]>
</script>
