<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Author Robert Hillebrand - hillebrand@i-ways.de - i-ways sales solutions GmbH
 * Copyright i-ways sales solutions GmbH © 2015. All Rights Reserved.
 * License http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

/**
 * @var \Iways\PayPalPlus\Block\Onepage\Success $block
 */
?>
<?php if($block->isPUI()) : ?>
    <div class="ppp-pui">
        <p><?php echo __(
                'Please transfer the invoice amount to the given account within the payment deadline.'
            ); ?></p>
        <table>
            <tbody>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo __('Account holder:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $block->getAdditionalInformation('ppp_account_holder_name'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo __('Bank:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $block->getAdditionalInformation('ppp_bank_name'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo __('IBAN:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $block->getAdditionalInformation('ppp_international_bank_account_number'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo __('BIC:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $block->getAdditionalInformation('ppp_bank_identifier_code'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo __('Reference number:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $block->getAdditionalInformation('ppp_reference_number'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo __('Payment due date:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $block->getAdditionalInformation('ppp_payment_due_date'); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
<?php elseif ($block->isPPP()): ?>
    <div class="ppp-success"><?php echo __('<i>processed by PayPal</i>');?></div>
<?php endif; ?>