<?php if($this->isPUI()) : ?>
    <div class="ppp-pui">
        <p><?php echo Mage::helper('iways_paypalplus')->__(
                'Please transfer the invoice amount to the given account within the payment deadline.'
            ); ?></p>
        <table>
            <tbody>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo Mage::helper('iways_paypalplus')->__('Account holder:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $this->getAdditionalInformation('ppp_pui_account_holder_name'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo Mage::helper('iways_paypalplus')->__('Bank:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $this->getAdditionalInformation('ppp_pui_bank_name'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo Mage::helper('iways_paypalplus')->__('IBAN:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $this->getAdditionalInformation('ppp_pui_international_bank_account_number'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo Mage::helper('iways_paypalplus')->__('BIC:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $this->getAdditionalInformation('ppp_pui_bank_identifier_code'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo Mage::helper('iways_paypalplus')->__('Reference number:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $this->getAdditionalInformation('ppp_pui_reference_number'); ?>
                    </td>
                </tr>
                <tr>
                    <td class="ppp-pui-label">
                        <?php echo Mage::helper('iways_paypalplus')->__('Payment due date:'); ?>
                    </td>
                    <td class="ppp-pui-value">
                        <?php echo $this->getAdditionalInformation('ppp_pui_payment_due_date'); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
<?php elseif ($this->isPPP()): ?>
    <div class="ppp-success"><?php echo $this->__('<i>processed by PayPal</i>');?></div>
<?php endif; ?>