<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Author Robert Hillebrand - hillebrand@i-ways.de - i-ways sales solutions GmbH
 * Copyright i-ways sales solutions GmbH © 2015. All Rights Reserved.
 * License http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<button type="submit" id="place-order-button" title="<?php echo $this->__('Place Order') ?>"
        class="button btn-checkout"
        onclick="return false;">
    <span>
        <span><?php echo $this->__('Place Order') ?></span>
    </span>
</button>
<script type="text/javascript">
    $('place-order-button').observe('click', function () {
        if (payment.currentMethod == '<?php echo Iways_PayPalPlus_Model_Payment::METHOD_CODE; ?>') {
            if ($('checkout-agreements') != null) {
                if (checkout.loadWaiting != false) return;
                checkout.setLoadWaiting('review');
                params = Form.serialize($('checkout-agreements'));
                params.validate = true;
                var request = new Ajax.Request(
                    '<?php echo Mage::helper('iways_paypalplus')->getUrl('paypalplus/index/validate'); ?>',
                    {
                        method: 'post',
                        parameters: params,
                        onSuccess: function (transport) {
                            try {
                                response = eval('(' + transport.responseText + ')');
                            }
                            catch (e) {
                                response = {};
                            }
                            if (response.redirect) {
                                review.isSuccess = true;
                                window.ppp.doCheckout();
                                return;
                            }
                            if (response.success) {
                                review.isSuccess = true;
                                window.ppp.doCheckout();
                            }
                            else {
                                var msg = response.error_messages;
                                if (typeof(msg) == 'object') {
                                    msg = msg.join("\n");
                                }
                                if (msg) {
                                    alert(msg);
                                }
                                review.resetLoadWaiting(transport);
                            }
                        },
                        onFailure: checkout.ajaxFailure.bind(checkout)
                    }
                );
            } else {
                review.isSuccess = true;
                window.ppp.doCheckout();
            }
        } else {
            review.save();
        }
    });
</script>